---

- hosts: all
  become: true
  tasks:


  - name: install packages
    tags: apache,php
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes

  - name: install packages for centOS
    tags: centOS,dnf,httpd
    package:
      name:
        - "{{ httpd_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: copy default html file for the site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
       src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
       dest: /usr/local/bin
       remote_src: yes
       mode: 0755
       owner: root
       group: root
